language: node_js
node_js:
  - "16"

branches:
  only:
    - main

install:
  - npm install

script:  
  - npm run build

before_deploy:
  - touch dist/.nojekyll  # Crea el archivo .nojekyll para evitar problemas en GitHub Pages
  - cp -r dist/* .  # Copia todos los archivos de dist a la raíz
  - cp -r dist/.* . || true  # Copia también archivos ocultos como .nojekyll
  - rm -rf dist  # Elimina la carpeta dist después de copiar el contenido

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Usa el token de GitHub configurado en Travis CI
  keep-history: true
  local_dir: .  # Despliega desde la raíz donde ahora están los archivos
  on:
    branch: main
