language: node_js
node_js:
  - "16"  # Cambia a la versión de Node.js que usas en tu proyecto

# Solo ejecuta el build en la rama main cuando hay un push
branches:
  only:
    - main

install:
  - npm install  # Instala las dependencias

script:  
  - npm run build  # Construye el proyecto (esto genera la carpeta dist)

before_deploy:
  - mv dist/* .  # Mueve el contenido de dist al root del proyecto
  - rm -rf dist  # Elimina la carpeta dist después de mover el contenido

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Usa el token de GitHub configurado en Travis CI
  keep-history: true
  local-dir: .  # Usa el root del proyecto después de mover los archivos de dist
  on:
    branch: main  # Solo se ejecuta en push a la rama main
