language: node_js
node_js:
  - "16"

branches:
  only:
    - main

install:
  - npm install

script:  
  - npm run build

before_deploy:
  - touch dist/.nojekyll  # Evita problemas de GitHub Pages con archivos y carpetas
  - mv dist/* .  # Mueve el contenido de dist a la raíz del proyecto
  - mv dist/.* .  # Mueve archivos ocultos como .nojekyll a la raíz también
  - rm -rf dist  # Elimina la carpeta dist después de mover el contenido

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Usa el token de GitHub configurado en Travis CI
  keep-history: true
  local_dir: .  # Despliega desde la raíz donde ahora están los archivos
  on:
    branch: main
